from pathlib import Path
p=Path('src/core/anims.js');s=p.read_text(encoding='utf-8');s=s.replace("    if (name === 'slot') {","    if (name === 'node' && bounds.nodeTarget) {\n      const target=bounds.nodeTarget.clone();\n      return {pos:target.clone().add(new THREE.Vector3(-.25,-.13,.30)),tgt:target};\n    }\n    if (name === 'slot') {")
s=s.replace('      const mat = mesh.material;','      const mats = (Array.isArray(mesh.material) ? mesh.material : [mesh.material]).map(mat=>({mat,opacity:mat.opacity,transparent:mat.transparent}));')
s=s.replace('      const wasTransparent = mat.transparent;\n      mat.transparent = true;\n      mat.opacity = 0;','      for(const {mat} of mats){mat.transparent=true;mat.opacity=0;}')
s=s.replace('          mat.opacity = e;','          for(const {mat,opacity} of mats) mat.opacity=e*opacity;')
s=s.replace('onDone: () => { mesh.position.y = baseY; mat.transparent = wasTransparent || mat.isMeshPhysicalMaterial; if (!mat.transparent) mat.opacity = 1; },','onDone: () => { mesh.position.y = baseY; for(const {mat,opacity,transparent} of mats){mat.opacity=opacity;mat.transparent=transparent;} },')
p.write_text(s,encoding='utf-8')
p=Path('src/core/buildshelf.js');s=p.read_text(encoding='utf-8').replace('new THREE.InstancedMesh(geo, mat, count)','new THREE.InstancedMesh(geo, Array.isArray(mat) ? mat.map(m=>m.clone()) : mat.clone(), count)');s=s.replace('bounds: { W, H, D: DEPTH }',"bounds: { W, H, D: DEPTH, nodeTarget: new THREE.Vector3(x0 + .016, .02 + Math.max(0, decks.findIndex((d,k)=>k>0 && d!=='none')) * LEVEL_PITCH, zPost) }")
p.write_text(s,encoding='utf-8')
p=Path('src/ui/hud.js');s=p.read_text(encoding='utf-8').replace("['slot', '槽口']","['slot', '槽口'], ['node', '节点近看']");s=s.replace('  function syncReadout(c, stats) {',"  function syncReadout(c, stats) {\n    const nodeButton=hudRight.querySelector('[data-view=\"node\"]');\n    if(nodeButton) nodeButton.hidden=c.bays===undefined;");s=s.replace('· 主型材总长 <b>${stats.profileLengthM.toFixed(1)} m</b>`;','· 主型材总长 <b>${stats.profileLengthM.toFixed(1)} m</b><br><span>节点与隐藏连接为示意 · 不作为加工、采购或承重依据</span>`;');p.write_text(s,encoding='utf-8')
p=Path('src/main.js');s=p.read_text(encoding='utf-8').replace('      const vp = anims.viewPos(name, active().bounds);','      const vp = anims.viewPos(name, active().bounds);');s=s.replace('    const vp = anims.viewPos(name, active().bounds);','    if(name === \'node\') { controls.autoRotate=false; anims.explode(current.groups,false); }\n    const vp = anims.viewPos(name, active().bounds);',1);s=s.replace("const viewMatch = location.hash.match(/^#rod\\/([a-z]+)/);","const viewMatch = location.hash.match(/^#(?:rod|profile)\\/([a-z]+)/);");p.write_text(s,encoding='utf-8')
# Format the generated shape factory for maintainability.
p=Path('src/core/profiles.js');s=p.read_text(encoding='utf-8');a=s.index('  const hw =');b=s.index('/** 层板条截面');chunk=s[a:b].replace('   ','\n  ').replace('  /**','\n/**');s=s[:a]+chunk+'\n'+s[b:];p.write_text(s,encoding='utf-8')
